
service: minesweeper

plugins: 
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-2
  environment:
    USER_NAME_DYNAMODB_TABLE: ${self:service}-${self:provider.stage}
    JWT_SECRET: ${file(./secrets.json):JWT_SECRET}
    DB: ${file(./secrets.json):DB}

functions:  
  login:
    handler: auth/authHandler.login
    events:
      - http:
          path: auth/login
          cors: true
          method: post
  
  register:
    handler: auth/authHandler.register
    events:
      - http:
          path: auth/register
          cors: true
          method: post


  createTable:
    handler: table/TableHandler.createTable
    events:
      - http:
          method: post
          cors: true
          path:  table/createTable

  saveTable:
    handler: table/TableHandler.saveTable
    events:
      - http:
          method: put
          cors: true
          path: table/saveTable

  AllTables:
    handler: table/TableHandler.AllTables
    events:
      - http:
          method: get
          cors: true
          path:  table/AllTables

  loadTable:
    handler: table/TableHandler.loadTable
    events:
      - http:
          method: get
          cors: true
          path:  table/loadTable/{_id}

  scores:
    handler: table/TableHandler.scores
    events:
      - http:
          path: scores
          method: get
          cors: true

  allDataUser:
    handler: user/UserHandler.dataUser
    events:
      - http:
          path: dataUser
          method: get
          cors: true