
service: minesweeper

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-2
  
  environment:
    USER_NAME_DYNAMODB_TABLE: ${self:service}-${self:provider.stage}
  
  iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:*:*:table/${self:service}"

resources:
  Resources:
    minesweeperTable:
      type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USER_NAME_DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: tableId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: tableId
            KeyType: RANGE
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1  



functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
        path: /createuser
        method: post 
        
#    