
service: minesweeper

plugins: 
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-2
  environment:
    USER_NAME_DYNAMODB_TABLE: ${self:service}-${self:provider.stage}
    JWT_SECRET: ${file(./secrets.json):JWT_SECRET}
    DB: ${file(./secrets.json):DB}

functions:  
  login:
    handler: auth/authHandler.login
    events:
      - http:
          path: auth/login
          method: post
          cors: true
  
  register:
    handler: auth/authHandler.register
    events:
      - http:
          path: auth/register
          method: post
          cors: true

  profile:
    handler: user/UserHandler.myProfile
    events:
      - http:
          path:  user/myProfile
          method: get
          cors: true

  createTable:
    handler: table/TableHandler.createTable
    events:
      - http:
          path:  table/createTable
          method: post
          cors: true

  saveTable:
    handler: table/TableHandler.saveTable
    events:
      - http:
          path:  table/saveTable
          method: put
          cors: true

  AllTables:
    handler: table/TableHandler.AllTables
    events:
      - http:
          path:  table/AllTables
          method: get
          cors: true

  loadTable:
    handler: table/TableHandler.loadTable
    events:
      - http:
          path:  table/loadTable
          method: get
          cors: true

  scores:
    handler: table/TableHandler.scores
    events:
      - http:
          path: scores
          method: get
          cors: true